### ISSUE TITLE
groundTruth.txt of Scenario04-02 seems buggy

### ISSUE THREAD

**Issue by MarvinLer** [Stephlat/dataChallengePerception#2]
There are roughly 40 timesteps for the ground truth file of the Scenario04-02 (63 lines) of the AVDIAR dataset while the video is 2:24 long. Is there another version with more information or are we supposed to work with this one ? (in that case should we expect similar cases in the private test set ?)

**Comment by ragondyn** [comment]
Thanks for sharing your remark,

Indeed, there is a bug in the ground truth, please don't consider this video anymore. We will make sure that the data selected for final evaluation doesn't have similar (or any) problems.

Good luck!

**Comment by MarvinLer** [comment]
Thanks for your very quick answer!
